name: 'Resharper Inspection Summary'
description: 'Summarises Resharper inspection results'
inputs:
  results-xml-path:
    description: 'The path to the XML output of the Resharper inspection'
    required: true
  results-path:
    description: 'The location to output Resharper results to'
    required: true
outputs:
  errors:
    description: 'The total number of errors found'
  warnings:
    description: 'The total number of warnings found'
  suggestions:
    description: 'The total number of suggestions found'
  hints:
    description: 'The total number of hints found'
  results-summary-json-path:
    description: 'The path to the JSON summary of the Resharper inspection'

runs:
  using: 'node12'
  main: 'index.js'