name: 'Resharper Inspect'
description: 'Runs Resharper inspection on provided solution'
inputs:
  inspectcode-path:
    description: 'The location of the Resharper Inspect Code executable'
    required: true
  minimum-severity:
    description: 'The minimum severity level to report. One of [INFO, HINT, SUGGESTION, WARNING, ERROR]'
    required: true
    default: WARNING
  results-path:
    description: 'The location to output Resharper results to'
    required: true
  solution-path:
    description: 'The path to the .NET solution'
    required: true
outputs:
  results-xml-path:
    description: 'The path to the XML output of the Resharper inspection'

runs:
  using: 'node12'
  main: 'index.js'