on: [push, pull_request]

jobs:
  resharper:
    runs-on: windows-latest
    name: Resharper
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup Resharper
      id: setup_resharper
      uses: .\actions\setup-resharper
      with:
        resharper-version: '2019.2.2'
    - name: Resharper Inspect
      id: resharper_inspect
      uses: .\actions\resharper-inspect
      with:
        inspectcode-path: "${{ steps.setup_resharper.outputs.inspectcode-path }}"
        solution-path: .\Sample\Sample.sln
    - name: Upload Resharper Results
      uses: actions/upload-artifact@v1
      with:
        name: resharper
        path: .\.output\resharper