on: 
  push:
    branches:
      - master

jobs:
  resharper:
    runs-on: windows-latest
    name: Resharper
    steps:

    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup Nuget
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Restore packages
      run: nuget restore .\Sample\Sample.sln

    - name: Setup Resharper
      run: nuget install JetBrains.ReSharper.CommandLineTools -OutputDirectory .\.tools -ExcludeVersion -Source https://api.nuget.org/v3/index.json

    - name: Run inspection
      id: resharper_inspect
      uses: .\actions\resharper-inspect
      with:
        inspectcode-path: .\.tools\JetBrains.ReSharper.CommandLineTools\tools\inspectcode.exe
        results-path: .\.resharper
        solution-path: .\Sample\Sample.sln
        minimum-severity: HINT

    - name: Summarise inspection results
      id: resharper_inspection_summary
      uses: .\actions\resharper-inspection-summary
      with:
        results-xml-path: ${{ steps.resharper_inspect.outputs.results-xml-path }}
        results-path: ${{ steps.setup_resharper.outputs.results-path }}

    - name: Print totals
      run: |
        echo "Errors: ${{ steps.resharper_inspection_summary.outputs.errors }}"
        echo "Warnings: ${{ steps.resharper_inspection_summary.outputs.warnings }}"
        echo "Suggestions: ${{ steps.resharper_inspection_summary.outputs.suggestions }}"
        echo "Hints: ${{ steps.resharper_inspection_summary.outputs.hints }}"

    - name: Upload inspection results
      uses: actions/upload-artifact@v1
      with:
        name: resharper
        path: .\.resharper

    - name: Apply inspection thresholds
      uses: .\actions\resharper-inspection-threshold
      with:
        results-summary-json-path: ${{ steps.resharper_inspection_summary.outputs.results-summary-json-path }}
        error-threshold: 1