on: [push]

jobs:
  resharper:
    runs-on: windows-latest
    name: Resharper
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Resharper Inspect
      id: resharper_inspect
      uses: .\resharper-inspect
      with:
        solution-path: .\Sample\Sample.sln
    - name: Upload Resharper Results
      uses: actions/upload-artifact@v1
      with:
        name: resharper
        path: .\.output\resharper