on: [push]

jobs:
  hello_windows_job:
    runs-on: windows-latest
    name: A job to say hello from Windows
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Hello world action step
      id: hello
      uses: ./hello-world
      with:
        who-to-greet: 'Mona the Octocat'

  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Hello world action step
      id: hello
      uses: ./hello-world
      with:
        who-to-greet: 'Mona the Octocat'